GET  http://localhost:3333/orphanages HTTP/1.1
####
GET  http://localhost:3333/orphanages/1 HTTP/1.1
####
POST http://localhost:3333/orphanages HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Outro lar
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="latitude"

-27.2104839
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longitude"

-49.625111
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="about"

Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="instructions"

Venha como se sentir a vontade e traga muito amor e paciência para dar.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="opening_hours"

Segunda à Sexta
8h às 18h
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="open_on_weekends"

false
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1 copy.png"
Content-Type: image/png

< ./1 copy.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
####
POST http://localhost:3333/orphanages HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Orf. Esperança
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="latitude"

-16.243946
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longitude"

-47.962101
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="about"

Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="instructions"

Venha como se sentir a vontade e traga muito amor e paciência para dar.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="opening_hours"

Segunda à Sexta
8h às 18h
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="open_on_weekends"

false
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1 copy.png"
Content-Type: image/png

< ./1 copy.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
####
POST http://localhost:3333/orphanages HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Lar de Cipriana
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="latitude"

-16.2497132
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="longitude"

-47.953611854
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="about"

Presta assistência a crianças de 06 a 15 anos que se encontre em situação de risco e/ou vulnerabilidade social.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="instructions"

Venha como se sentir a vontade e traga muito amor e paciência para dar.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="opening_hours"

Segunda à Sexta
8h às 18h
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="open_on_weekends"

false
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="1 copy.png"
Content-Type: image/png

< ./1 copy.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
